### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by gillesosx** [aeguana/PyFileMaker#20]
Hi,

I don't know if the library has been tested with Python 3.x, but I tried installing it, I got:

Downloading/unpacking PyFileMaker
  Downloading PyFileMaker-3.3.tar.gz
  Running setup.py (path:/tmp/pip-build-5snog6ws/PyFileMaker/setup.py) egg_info for package PyFileMaker
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-5snog6ws/PyFileMaker/setup.py", line 4, in <module>
        from PyFileMaker import __version__
      File "/tmp/pip-build-5snog6ws/PyFileMaker/PyFileMaker/__init__.py", line 18
        print "Unable to load the EXPAT library. You need to have it installed"
                                                                              ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-5snog6ws/PyFileMaker/setup.py", line 4, in <module>

    from PyFileMaker import __version__

  File "/tmp/pip-build-5snog6ws/PyFileMaker/PyFileMaker/__init__.py", line 18

    print "Unable to load the EXPAT library. You need to have it installed"

Is there a version compatible with Python 3 ?

Thanks

Gilles Plante

**Comment by gillesosx** [comment]
Hi,

anything new about that ?

Thanks

**Comment by ais** [comment]
Per an email with @jasonaeguana:
> [...] we're not really actively supporting it at the moment I'm afraid, unless we have a commercial incentive to do so i.e. a project on Python3 that warrants it!

**Comment by gillesosx** [comment]
Thanks for your reply.

Gilles Plante | ingp

De : overkillx<mailto:notifications@github.com>
Envoyé le :5 octobre 2017 10:12
À : aeguana/PyFileMaker<mailto:PyFileMaker@noreply.github.com>
Cc : gillesosx<mailto:gillesosx@outlook.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [aeguana/PyFileMaker] Compatibility with Python 3 (#20)


Per an email with @jasonaeguana<https://github.com/jasonaeguana>:

[...] we're not really actively supporting it at the moment I'm afraid, unless we have a commercial incentive to do so i.e. a project on Python3 that warrants it!

**Comment by GgFigura** [comment]
Dear all,
I'm have the same issue to install PyFileMaker on Python3 and I wonder whether Python3 is now compatible.
